### ISSUE TITLE
"https://www.example.com**" parses as a single link?

### ISSUE THREAD

**Issue by tmladek** [robinst/linkify#11]
I ran into a bug in my application which I traced down to `linkify` (v0.4.0) treating the string `https://www.example.com**` (appearing due to markdown emphasis, i.e. `**Visit example at https://www.example.com**`) as a single link.

I am not sure whether this is the correct behavior or not - strictly speaking, I imagine it could be a valid URL according to RFCs, but the examples on the first page of the docs make me think this might not have been intended:

>In `http://example.com/.` the link should not include the trailing dot
>`http://example.com/,` should not include the trailing comma

**Comment by robinst** [comment]
Looking at https://tools.ietf.org/search/rfc3986#section-2.2, `*` is part of sub-delims, so it can be part of a URL. Having said that, this library currently doesn't include trailing `,` (which is also a sub-delim), so we could exclude trailing `*` too.

But before I do that, can I ask: Are you linkifying first, and then Markdown parsing? If yes, I would recommend doing the parsing first, and then linkifying only on the resulting text nodes.

**Comment by tmladek** [comment]
Yes, exactly; or the period (e.g. "https://example.com/.") which is arguably even more likely to pop up in some context as a valid URL, "." denoting the "current directory" of unix paths, and so on - so usability-wise, I think * should be excluded also.

As to your question, yes I am, because I'm doing more to the markdown than just linkifying it, so it made sense to put it in the same "preprocessing" step - but you are right in that linkifying the HTML output would probably fix this issue also.

**Comment by robinst** [comment]
@tmladek Released a fix for this in version 0.5.0, please have a look!
