### ISSUE TITLE
Are wildcard operators allowed in links?

### ISSUE THREAD

**Issue by mre** [robinst/linkify#37]
We received an interesting issue for lychee here: https://github.com/lycheeverse/lychee/issues/604.
The gist is that links with wildcard operators (e.g. https://*.example.com) get properly extracted by linkify, but we cannot easily check them with lychee.

We now wonder if we should handle the exclusion of such wildcard URLs on our end or whether it's better to discard them right away with linkify.
From my perspective, these are valid links, so linkify is correct, but the behavior might be surprising to downstream users. Perhaps another config option could be introduced which would allow to skip such wildcard URLs:

```rust
let finder = LinkFinder::new().wildcards(false);
```

However there are [other sub-delimiters](https://stackoverflow.com/a/45872342/270334), so I could understand if such cases won't be handled by linkify. In this scenario we would filter them in lychee instead.

**Comment by mre** [comment]
Created a PR with the mentioned changes here: https://github.com/robinst/linkify/pull/38

**Comment by robinst** [comment]
Those kinds of URLs are no longer extracted by linkify with 0.9.0: https://github.com/robinst/linkify/blob/main/CHANGELOG.md#090---2022-07-11
