### ISSUE TITLE
Handle backslashes properly

### ISSUE THREAD

**Issue by laralove143** [robinst/linkify#47]
In a file like
```rs
example.com/thisisactually\
verylong
```
is detected as `example.com/thisisactually` where it should be `example.com/thisisactuallyverylong` and the newline should be ignored like Rust does

**Comment by robinst** [comment]
Hi. I don't want to add markup-specific logic to this library. Note that GitHub behaves the same way here (well it includes the backslash in the link too, but not the second line):

https://example.com/thisisactually\
verylong
