### ISSUE TITLE
Does not detect parameters in links 

### ISSUE THREAD

**Issue by A6GibKm** [robinst/linkify#59]
The library does not detect parameters in links, e.g. `upi://pay?pa=XXXXXXX&pn=XXXXX` will only find the link `upi://pay`.  instead of `upi://pay?pa=XXXXXXX&pn=XXXXX`. Its reasonable that if there is a single trailing `?` (e.g. `Open https::/example.com?`) it won't be part of the link but otherwise it is likely the segment following it will be part of the link.

See https://gitlab.gnome.org/World/decoder/-/issues/65

**Comment by robinst** [comment]
Thanks! It already worked when there was a slash like this: `upi://pay/?pa=XXXXXXX&pn=XXXXX`

But if the path was empty it didn't work yet. Raised a PR to fix.

**Comment by robinst** [comment]
Fix released in version 0.10.0: https://github.com/robinst/linkify/blob/main/CHANGELOG.md#0100---2023-06-24

**Comment by A6GibKm** [comment]
Thanks, updated my app to make use of 0.10.
