### ISSUE TITLE
`non_exhaustive` attribute for `LinkKind`

### ISSUE THREAD

**Issue by Colerar** [robinst/linkify#60]
[`non_exhaustive` (RFC 2008)](https://rust-lang.github.io/rfcs/2008-non-exhaustive.html) attribute was added in Rust v1.40.0 (2019-12-19).

```rust
pub enum LinkKind {
    Url,
    Email,
    #[doc(hidden)]
    __Nonexhaustive,
}
```

The code above can be written idiomatically as:

```rust
#[non_exhaustive]
pub enum LinkKind {
    Url,
    Email,
}
```

**Comment by robinst** [comment]
Thanks, done!
