### ISSUE TITLE
Protocol-relative URLs

### ISSUE THREAD

**Issue by nivekuil** [robinst/linkify#9]
`assert_linked("//foo", "|//foo|");` currently fails, but according to RFC3986 it should count as a valid URL. See also https://www.paulirish.com/2010/the-protocol-relative-url/ -- I still see a few of these in the wild.

**Comment by robinst** [comment]
Hm yeah, true.

> I still see a few of these in the wild.

Just to clarify, you see these being written by people in plain text?

I'm inclined to close this as won't fix, as it's a non-trivial amount of work and would slow down other matching a tiny bit, for relatively little gain.
